sources:
  - name: site-one
    use_js: true
    start_urls:
      - https://example.com/real-estate
    listing_patterns:
      - "/listing/"
  - name: site-two
    use_js: false
    start_urls:
      - https://example.org/properties
    listing_patterns:
      - "property-\\d+"
